server:
  port: 10000

spring.datasource.url: jdbc:mysql://sh-cynosdbmysql-grp-ky91abiy.sql.tencentcdb.com:25742
spring.datasource.username: test
spring.datasource.password: Test111222333
spring.datasource.driverClassName: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.touale.ve.entity.battle

spring:
  freemarker:
    checkTemplateLocation=false:


springfox:
  documentation:
    swagger-ui:
      enabled: true

